apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
  - port: 30001
    nodePort: 30002
    targetPort: nodejs-port
    protocol: TCP
  selector: 
    app: hello-world
  type: NodePort