apiVersion: v1
kind: Pod
metadata:
  name: pod-python
  labels:
    app: hello-world-python
spec: 
  containers:
  - name: nags-python-app
    image: nagasaim/python-docker-dev
    ports:
    - containerPort: 5000