apiVersion: v1
kind: Service
metadata:
  name: pod-python-service
spec:
  ports:
  - port: 31234
    nodePort: 31235
    targetPort: 5000
    protocol: TCP
  selector:
    app: hello-world-python
  type: NodePort